### ISSUE TITLE
设计目标

### ISSUE THREAD

**Issue by gnh123** [gnh123/scheduler#1]
## 抽象来讲需要解决的问题点
1. 定时任务
2. 延时任务
3. DAG
4. 异步重试任务

## 具体点的业务
1. 多个机器运行一个脚本，清理下所有机器的日志
2. 定时用脚本刷数据库的数据
3. 通过http定时扫描订单

## 多runtime
1. exec， 多语言支持，但是性能较差
4. http服务，多语言支持，性能较好(被动模式)
5. grpc(可选，不一定在第一个版本实现)
6. plugin(可选，不一定在第一个版本实现)

## 竖向看构架
1. crud
  1.1 cli
  1.2 web
2. runtime层，提供task的执行，每个任务是task。
  2.1 exec
  2.2 websocket
4. 分布式锁层，第一个版本由etcd实现，如果etcd性能压测不行，再优化。
5. 服务注册与发现

## 横向看构架
1. runtime 主要是执行task
2. gate 长连接协议接入层(为了，支持混合部署方式，master在线上，slave在线下。数据流向是slave连接router)
3. mjobs 获取etcd里面的数据，分发任务。(mjobs和gate必须要能访问同一个etcd)
## slave的命令行设计
1. endpoint 填写 router地址
## 命令行设计
scheduler start 配置文件.  #创建新的dag任务，并且运行
scheduler stop 配置文件.  #停止dag任务
scheduler rm 配置文件.     #删除dag任务
scheduler run 配置文件.    #运行已存在的任务，如果不存在会返回错误
scheduler status 获取任务的状态

## 多时间触发
1. cron
4. 周期任务
6. 日历

## 报警纬度
1. 失败报警
2. 超时报警
3. 无可用机器报警

## 报警纬度
1. 飞书
2. 钉钉
3. 微信

## 执行方式
1. 单机，随机找一台执行
2. 广播，所有的机器都会执行
3. 
## 重试策略
1. 重试次数
3. 重试间隔

## http 配置文件
```yaml
apiVersion: v0.0.1
trigger:
  cron: "* * * * * *" #每秒触发一次
executer:
  http:
    method: post
    scheme: https
    host:    #不写，默认执行器的ip
    port:    #不写，默认80
    headers:
    - name: Bid
    - value: xxxx
    body: 
```

## shell 配置文件
commond和args只要设置一个就行。
```yaml
apiVersion: v0.0.1
trigger:
  cron: "* * * * * *" #每秒触发一次
executer:
  shell:
    commond: echo "hello" #command和args的作用是等价的，唯一的区别是命令放在一个字符串或者slice里面。
    args:
    - echo
    - "hello"
```
## lambda
```yaml
apiVersion: v0.0.1
trigger:
  cron: "* * * * * *" #每秒触发一次
executer:
  lambda:
    funcName: study
    args:
    -
```
## 高可靠
通过分布式架构、数据三备份、消息At-least-once delivery、Failover和定期轮检等手段，保证任务调度和运行的高可靠。
## 参数资料
https://help.aliyun.com/document_detail/148186.html
https://tech.youzan.com/tsp_schedule/
https://tech.youzan.com/queuing_delay/
